services:
  # Backend Flask service
  backend:
    image: yasyn/attendance-backend
    container_name: attendance-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - uploads-data:/app/uploads
    networks:
      - attendance-network

  # Next.js frontend service
  frontend:
    image: yasyn/attendance-frontend
    container_name: attendance-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
      BACKEND_URL: http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - attendance-network

  # PostgreSQL database service
  db:
    image: postgres:17-alpine
    container_name: attendance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yasyn19
      POSTGRES_DB: attendance_db
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - attendance-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

# Volumes to persist data
volumes:
  postgres-data:
  uploads-data:

# Network for the services to communicate
networks:
  attendance-network:
    driver: bridge
